// Auto-build the shotlist + Master Shot Briefs from an approved scene.
//
// Pipeline:
//   approved scene fountain
//     + project tone + showrunner_notes + production rules (prefer / avoid)
//     + cast bible + DNA
//     + character_arcs / scene-level emotional beat (when available)
//   →  shotlist agent (LLM)
//   →  array of Master Shot Briefs, each tagged autoGenerated=true
//
// This module never mutates an already-user-edited brief without explicit
// confirmation. The router, adapters, tags, weights, gate, results, and
// model profiles are NOT touched here — auto-build is purely an upstream
// population layer.

import { writeFileSync, mkdirSync } from "node:fs";
import { supabase } from "../../db/client.js";
import { callLLM, extractJSON } from "../../llm/provider.js";
import { config } from "../../config.js";
import { getProductionRules } from "./productionRules.js";
import {
  classifyBriefFields,
  strictCleanBrief,
  type StrictRemoval,
} from "./briefStrict.js";
import { filmableDescriptors } from "./composer.js";
import { validateBrief } from "./briefValidator.js";
import type {
  BriefCharacter,
  MasterShotBrief,
  ShotTag,
  VisualWeight,
} from "./types.js";

type Meta = Record<string, unknown>;
const safeMeta = (m: unknown): Meta => ((m ?? {}) as Meta);

const VALID_TAGS: ShotTag[] = ["ENV", "BEH", "CHAR", "TRANS", "PRE", "VO", "KEY", "ACT", "INT", "EXT"];

export interface AutoBuildOptions {
  /** "replace" overwrites every existing brief; "fill-empty" keeps existing. */
  mode?: "replace" | "fill-empty";
  /** Required true to overwrite briefs that already have userEdited=true. */
  confirmOverwriteUserEdits?: boolean;
  /** Optional steering notes for THIS auto-build pass. */
  notes?: string;
  /**
   * Source-strict mode. The agent gets a stricter prompt + every generated
   * brief is run through briefStrict's classifier; speculative fields are
   * stripped from the main brief and quarantined under nonCanonNotes.
   */
  sourceStrict?: boolean;
}

export interface AutoBuildReport {
  briefs: MasterShotBrief[];
  /** Indices that already had userEdited=true and were NOT overwritten. */
  preserved: number[];
  /** Slugline + scene number context. */
  sceneSlugline: string;
}

interface RawShot {
  index?: number;
  // The seven photographable fields (preferred).
  primaryImage?: string;
  cameraSees?: string;
  frame?: string;
  light?: string;
  texture?: string;
  lockedDetails?: string;
  // Legacy fields (still accepted for back-compat).
  shotPurpose?: string;
  storyBeat?: string;
  emotionalBeat?: string;
  characters?: Array<{ name?: string; description?: string; wardrobe?: string }>;
  location?: string;
  timeOfDay?: string;
  lighting?: string;
  colorPalette?: string;
  cameraFraming?: string;
  lensSuggestion?: string;
  cameraMovement?: string;
  action?: string;
  performanceDirection?: string;
  dialogue?: string;
  props?: string[];
  productionDesign?: string;
  visualMotif?: string;
  continuityNotes?: string;
  aspectRatio?: string;
  durationSec?: number;
  outputType?: "video" | "still" | "either";
  safetyNotes?: string;
  shotTags?: string[];
  visualWeight?: Partial<VisualWeight>;
}

/**
 * Run the shotlist agent on the scene's fountain. The LLM is asked to break
 * the scene into 3–6s cinematic shot units and fill every brief field. The
 * project's prefer / avoid rules + character DNA are injected verbatim.
 */
async function callShotlistAgent(args: {
  projectTitle: string;
  episodeNumber: number | null;
  episodeTitle: string | null;
  sceneOrd: number;
  slugline: string;
  fountain: string;
  tone: string[];
  showrunnerNotes: string | null;
  prefer: string[];
  avoid: string[];
  cast: Array<{ name: string; description: string; wardrobe?: string }>;
  steering?: string;
  sourceStrict?: boolean;
  /** Project tier — when "micro_drama" we switch the agent's directives
   *  to retention-first rules (vertical, faces/hands/phones, hard
   *  cliffhanger pull, no establishing shots). */
  projectType?: string;
}): Promise<RawShot[]> {
  const system = [
    "You are the SHOTLIST agent for an AI-assisted cinematic production",
    "pipeline under showrunner control. You break ONE approved screenplay",
    "scene into a list of cinematic shot units — 3 to 6 seconds each — that",
    "an AI video model can actually render well.",
    "",
    "HARD RULES:",
    "• NEVER generate a single long prompt for the whole scene.",
    "• Default shot length 3–6s. Longer shots only when motion is low,",
    "  hands aren't doing complex work, characters are few, and no",
    "  complex dialogue is required.",
    "• Prefer reaction shots, voiceover-driven shots, behavioural inserts,",
    "  cutaways, objects-in-frame, atmosphere and negative space over",
    "  long lip-synced dialogue takes.",
    "• If a scene has dialogue, distribute it across the shotlist — use",
    "  short in-shot lines (≤ ~12 words) only where the take fits, and",
    "  prefer reaction / VO over forced lip-sync.",
    "• Preserve continuity: characters & wardrobe stay consistent shot",
    "  to shot; locations match the slugline.",
    "",
    "PER SHOT, you MUST return the SEVEN PHOTOGRAPHABLE FIELDS:",
    "",
    "  1. primaryImage  — ONE sentence. The image the audience remembers.",
    "       GOOD: 'The last lights of San José dissolving through a rain-",
    "             covered rear window.'",
    "       GOOD: 'A clothed woman at the edge of a luxury pool she has",
    "             not entered.'",
    "       BAD : 'Margot feels the weight of leaving.'",
    "       BAD : 'Effortful calm as the city fades.'",
    "",
    "  2. cameraSees    — 2–4 sentences. Observable visual facts only.",
    "                     What is literally in the frame. No interpretation.",
    "                     GOOD: 'Rain-flecked glass in the foreground. Two",
    "                     sodium streetlights smearing into the wet pane.",
    "                     The lower edge of a leather seat in the corner.'",
    "                     BAD : 'A sense of loneliness fills the frame.'",
    "",
    "  3. action        — ONE continuous motion. Present tense. Filmable.",
    "                     GOOD: 'Hands rest open on the lap; the phone",
    "                     screen dims and fades to black.'",
    "                     BAD : 'She struggles with restraint.'",
    "",
    "  4. frame         — Composition + camera placement, one descriptive",
    "                     line. Include framing (CU/MS/WS/INSERT/POV/OTS),",
    "                     lens, height, angle, movement.",
    "                     GOOD: 'Static medium shot, 35mm anamorphic,",
    "                     2.39:1, locked off behind the rear window glass.'",
    "",
    "  5. light         — Observable lighting conditions. Source, direction,",
    "                     quality, palette.",
    "                     GOOD: 'Sodium streetlight strobing through wet",
    "                     glass; near-total interior darkness; blue-grey",
    "                     palette pulled cold.'",
    "",
    "  6. texture       — Materials, atmosphere, environmental detail.",
    "                     GOOD: 'Rain on glass; smeared amber halos; mist",
    "                     drifting beyond the canopy; cracked asphalt.'",
    "",
    "  7. lockedDetails — Props, wardrobe, continuity anchors. Comma list.",
    "                     GOOD: 'phone face-down on the seat; dark linen",
    "                     coat; carry-on bag against the door.'",
    "",
    "EVERY one of these fields MUST be photographable. If the camera",
    "cannot record it, do not write it. The validator will strip any",
    "interpretation at persist and surface a warning to the writer.",
    "",
    "ALSO return (used by the router, audit, and continuity systems):",
    "  characters[] (name + visible descriptor + wardrobe — NO biography),",
    "  location, timeOfDay, aspectRatio (16:9 default),",
    "  durationSec (3–6 default), outputType (video unless key frame),",
    "  dialogue (only if it fits in-shot, else empty), safetyNotes,",
    "  shotTags (one or more of ENV, BEH, CHAR, TRANS, PRE, VO, KEY,",
    "    ACT, INT, EXT), visualWeight (% per axis: environment, character,",
    "    object, cameraMovement, dialogue, action, atmosphere — sums near 100).",
    "",
    "Legacy fields (shotPurpose, storyBeat, emotionalBeat, performanceDirection,",
    "cameraFraming, lensSuggestion, cameraMovement, lighting, colorPalette,",
    "productionDesign, visualMotif, continuityNotes, props[]) may be returned",
    "for back-compat but the SEVEN PHOTOGRAPHABLE FIELDS take precedence and",
    "are what the prompt composer reads from.",
    "",
    "CHARACTERS[].description — FILMABLE ONLY:",
    "  This field is the on-screen visual descriptor for THIS shot.",
    "  Acceptable: age tier, gender presentation, build, hair, eyes, skin,",
    "  posture, wardrobe — anything a camera can see.",
    "  FORBIDDEN: profession (therapist, surgeon, cop), psychology (grief,",
    "  observant, perceptive, watchful as trait), relationships / backstory",
    "  (widow, eighteen months out, daughter's death), or story-context",
    "  ('not to heal but to feel something', 'professional training makes",
    "  her…'). Those belong in the character bible, NEVER on a per-shot",
    "  brief. Example acceptable: '48, brunette, slim, dark linen coat'.",
    "  Example forbidden: 'A therapist eighteen months out from her",
    "  daughter's death. The most perceptive observer in any room.'",
    "",
    args.prefer.length
      ? `PREFER (showrunner production rules): ${args.prefer.join("; ")}.`
      : "",
    args.avoid.length
      ? `AVOID (showrunner production rules): ${args.avoid.join("; ")}.`
      : "",
    args.tone.length ? `TONE: ${args.tone.join(", ")}.` : "",
    args.showrunnerNotes ? `Showrunner notes:\n${args.showrunnerNotes.slice(0, 600)}` : "",
    args.steering ? `WRITER STEERING for THIS auto-build: """${args.steering}"""` : "",
    "",
    args.sourceStrict
      ? [
          "SOURCE-STRICT MODE — non-negotiable:",
          "• Use ONLY details present in the approved scene text + cast bible.",
          "• Do NOT invent wardrobe, props, locations, character actions, or",
          "  dialogue not found in the scene.",
          "• If a field cannot be filled safely from source, leave it empty.",
          "• Conservative production inferences (a generic shot-size for an",
          "  action implied by the scene; a 16:9 default; restraint lighting",
          "  for an established tonal palette) are allowed — invented",
          "  specifics are NOT.",
          "",
        ].join("\n")
      : "",
    args.projectType === "micro_drama"
      ? [
          "MICRO-DRAMA MODE — retention-first rules:",
          "• Vertical format. aspectRatio defaults to 9:16.",
          "• Prioritize faces, eyes, hands, phones, text messages, voice notes,",
          "  objects, doors, photographs. Tag these shots INSERT / BEH / CHAR.",
          "• AVOID wide establishing shots, large crowds, long exposition,",
          "  expensive environments, complex dialogue.",
          "• Clip length 3–5 seconds. Single beat per shot. No multi-action takes.",
          "• Every scene must contribute to the episode's HOOK / TWIST /",
          "  CLIFFHANGER pull — if a shot doesn't move retention, cut it.",
          "",
        ].join("\n")
      : "",
    "Return ONLY JSON: { \"shots\": [ { ...one shot object per element... } ] }",
  ]
    .filter(Boolean)
    .join("\n");

  const castBlock =
    args.cast.length === 0
      ? "(no cast declared on this scene — use unnamed background only)"
      : args.cast
          .map((c) => {
            const w = c.wardrobe ? ` — wardrobe: ${c.wardrobe}` : "";
            return `${c.name.toUpperCase()}: ${c.description}${w}`;
          })
          .join("\n");

  const user = [
    `Series: ${args.projectTitle}`,
    args.episodeNumber
      ? `Episode ${args.episodeNumber}${args.episodeTitle ? `: ${args.episodeTitle}` : ""}`
      : "",
    `Scene #${args.sceneOrd} — ${args.slugline}`,
    "",
    "CAST AVAILABLE FOR THIS SCENE (use these names verbatim; no invented characters):",
    castBlock,
    "",
    "APPROVED SCENE TEXT (Fountain):",
    args.fountain,
  ]
    .filter(Boolean)
    .join("\n");

  // 12000 tokens is enough headroom for ~9 shots × full per-shot schema.
  // The old 4500-token cap was truncating responses mid-JSON for any scene
  // with more than ~6 shots, surfacing as "did not return usable JSON".
  const MAX_TOKENS = 12000;

  // One LLM call, then one targeted retry if the parse fails. The retry
  // adds an explicit "JSON ONLY — no prose, no preamble" instruction so
  // the model can't drift into commentary on the next try.
  const attempt = async (extraInstruction?: string): Promise<{ raw: string; shots: RawShot[] | null }> => {
    const messages = [
      { role: "system" as const, content: system },
      { role: "user" as const, content: user },
    ];
    if (extraInstruction) {
      messages.push({ role: "user" as const, content: extraInstruction });
    }
    const r = await callLLM({
      model: config.SCENE_MODEL,
      messages,
      temperature: args.sourceStrict ? 0.2 : 0.4,
      maxTokens: MAX_TOKENS,
    });
    try {
      const parsed = extractJSON(r.text) as { shots?: RawShot[] };
      const shots = Array.isArray(parsed.shots) ? parsed.shots : null;
      return { raw: r.text, shots };
    } catch {
      return { raw: r.text, shots: null };
    }
  };

  let { raw, shots } = await attempt();
  if (!shots || shots.length === 0) {
    // Retry once with a hard JSON-only nudge.
    const retry = await attempt(
      [
        "Your previous response could not be parsed as JSON.",
        "Respond now with the JSON object ONLY — no markdown fences, no prose,",
        'no preamble. Schema: { "shots": [ { /* one shot object */ } ] }.',
      ].join("\n")
    );
    raw = retry.raw;
    shots = retry.shots;
  }

  if (!shots || shots.length === 0) {
    // Save the raw response so the writer / dev can see what the model
    // actually produced. The error message also embeds the first 240
    // characters so the failure is diagnosable directly from the UI.
    let dumpPath = "";
    try {
      mkdirSync("/tmp/toburt-llm-dumps", { recursive: true });
      const ts = new Date().toISOString().replace(/[:.]/g, "-");
      dumpPath = `/tmp/toburt-llm-dumps/shotlist-failed-${ts}.txt`;
      writeFileSync(dumpPath, raw ?? "(empty response)");
    } catch {
      /* dump is best-effort */
    }
    const snippet = (raw ?? "").trim().slice(0, 240);
    const len = (raw ?? "").length;
    throw new Error(
      `Shotlist agent did not return usable JSON (response length ${len}). ` +
        `First 240 chars: ${snippet || "(empty)"}` +
        (dumpPath ? ` — full response saved to ${dumpPath}` : "")
    );
  }
  return shots;
}

function s(v: unknown, fallback = ""): string {
  return typeof v === "string" && v.trim() ? v.trim() : fallback;
}
function n(v: unknown, fallback = 0): number {
  return typeof v === "number" && !Number.isNaN(v) ? v : fallback;
}

function normalizeTags(raw: unknown): ShotTag[] {
  if (!Array.isArray(raw)) return [];
  const set = new Set<ShotTag>();
  for (const t of raw) {
    if (typeof t !== "string") continue;
    const upper = t.toUpperCase() as ShotTag;
    if (VALID_TAGS.includes(upper)) set.add(upper);
  }
  return [...set];
}

function normalizeWeight(raw: unknown): VisualWeight | undefined {
  if (!raw || typeof raw !== "object") return undefined;
  const r = raw as Partial<Record<keyof VisualWeight, number>>;
  const out: VisualWeight = {
    environment: n(r.environment, 0),
    character: n(r.character, 0),
    object: n(r.object, 0),
    cameraMovement: n(r.cameraMovement, 0),
    dialogue: n(r.dialogue, 0),
    action: n(r.action, 0),
    atmosphere: n(r.atmosphere, 0),
  };
  const total = Object.values(out).reduce((a, b) => a + Math.max(0, b), 0);
  if (total <= 0) return undefined;
  // Normalize to 100.
  const scale = 100 / total;
  return {
    environment: Math.round(out.environment * scale),
    character: Math.round(out.character * scale),
    object: Math.round(out.object * scale),
    cameraMovement: Math.round(out.cameraMovement * scale),
    dialogue: Math.round(out.dialogue * scale),
    action: Math.round(out.action * scale),
    atmosphere: Math.round(out.atmosphere * scale),
  };
}

function clampDuration(d: number, outputType: string): number {
  if (outputType === "still") return 0;
  if (!d) return 5;
  return Math.max(2, Math.min(10, Math.round(d)));
}

function briefId(args: {
  projectTitle: string;
  episodeNumber: number | null;
  sceneOrd: number;
  shotIndex: number;
}): string {
  const series = args.projectTitle
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase();
  const ep = args.episodeNumber ? `EP${args.episodeNumber}_` : "";
  return `${series}_${ep}SC${String(args.sceneOrd).padStart(2, "0")}_SH${String(args.shotIndex).padStart(2, "0")}`;
}

/**
 * Map a raw shotlist entry into a fully-formed MasterShotBrief. Missing
 * fields fall back to sensible defaults so the brief always validates.
 */
function rawToBrief(args: {
  raw: RawShot;
  index: number;
  projectTitle: string;
  episodeNumber: number | null;
  episodeTitle: string | null;
  sceneOrd: number;
  slugline: string;
  fallbackCast: BriefCharacter[];
}): MasterShotBrief {
  const now = new Date().toISOString();
  const outputType = (args.raw.outputType === "still"
    ? "still"
    : args.raw.outputType === "either"
    ? "either"
    : "video") as MasterShotBrief["outputType"];
  // Sanitize at the write boundary: the shotlist agent has been observed
  // dumping character-bible biography into description ("a therapist
  // eighteen months out from her daughter's death..."). The brief is the
  // canonical record consumed by every downstream prompt, so we reduce
  // descriptions to filmable surface tokens here — never persist bio.
  const characters: BriefCharacter[] = Array.isArray(args.raw.characters)
    ? args.raw.characters
        .map((c) => {
          const rawDesc = s(c.description);
          return {
            name: s(c.name),
            description: rawDesc ? filmableDescriptors(rawDesc) : "",
            wardrobe: s(c.wardrobe) || undefined,
          };
        })
        .filter((c) => c.name)
    : args.fallbackCast;

  const draft: MasterShotBrief = {
    id: briefId({
      projectTitle: args.projectTitle,
      episodeNumber: args.episodeNumber,
      sceneOrd: args.sceneOrd,
      shotIndex: args.index,
    }),
    projectTitle: args.projectTitle,
    episodeNumber: args.episodeNumber,
    episodeTitle: args.episodeTitle,
    sceneOrd: args.sceneOrd,
    shotIndex: args.index,
    // Seven photographable fields (preferred).
    primaryImage: s(args.raw.primaryImage) || undefined,
    cameraSees: s(args.raw.cameraSees) || undefined,
    frame: s(args.raw.frame) || undefined,
    light: s(args.raw.light) || undefined,
    texture: s(args.raw.texture) || undefined,
    lockedDetails: s(args.raw.lockedDetails) || undefined,
    // Legacy fields (back-compat).
    shotPurpose: s(args.raw.shotPurpose, "(define the shot purpose)"),
    storyBeat: s(args.raw.storyBeat),
    emotionalBeat: s(args.raw.emotionalBeat),
    characters: characters.length ? characters : args.fallbackCast,
    location: s(args.raw.location, args.slugline),
    timeOfDay: s(args.raw.timeOfDay, "DAY"),
    lighting: s(args.raw.lighting),
    colorPalette: s(args.raw.colorPalette),
    cameraFraming: s(args.raw.cameraFraming, "MS"),
    lensSuggestion: s(args.raw.lensSuggestion, "35mm"),
    cameraMovement: s(args.raw.cameraMovement, "static"),
    action: s(args.raw.action),
    performanceDirection: s(args.raw.performanceDirection) || undefined,
    dialogue: s(args.raw.dialogue) || undefined,
    continuityNotes: s(args.raw.continuityNotes) || undefined,
    props: Array.isArray(args.raw.props)
      ? args.raw.props.filter((x): x is string => typeof x === "string")
      : undefined,
    productionDesign: s(args.raw.productionDesign) || undefined,
    visualMotif: s(args.raw.visualMotif) || undefined,
    aspectRatio: s(args.raw.aspectRatio, "16:9"),
    durationSec: clampDuration(n(args.raw.durationSec, 5), outputType),
    outputType,
    safetyNotes: s(args.raw.safetyNotes) || undefined,
    shotTags: normalizeTags(args.raw.shotTags),
    visualWeight: normalizeWeight(args.raw.visualWeight),
    autoGenerated: true,
    userEdited: false,
    createdAt: now,
    updatedAt: now,
  };
  // Write-time validator: strip interpretive / theme / psychology phrases
  // from every text field BEFORE persist. Warnings are stored on
  // brief.interpretiveWarnings; the composer's readiness gate surfaces
  // them as "Brief contains interpretation instead of photography."
  return validateBrief(draft).cleaned;
}

/** Read scene + project + episode + cast context the shotlist agent needs. */
async function loadAutoBuildContext(scriptId: string, sceneOrd: number) {
  const { data: script } = await supabase
    .from("scripts")
    .select("id, project_id, episode_id, metadata")
    .eq("id", scriptId)
    .single();
  if (!script) throw new Error("Script not found.");
  const { data: scene } = await supabase
    .from("script_scenes")
    .select("slugline, fountain, status, tags")
    .eq("script_id", scriptId)
    .eq("ord", sceneOrd)
    .maybeSingle();
  if (!scene?.fountain || (scene.fountain as string).trim().length < 20) {
    throw new Error(
      `Scene ${sceneOrd} has no approved script text yet — write the scene before auto-building shots.`
    );
  }
  const { data: proj } = await supabase
    .from("projects")
    .select("title, tone, showrunner_notes, metadata")
    .eq("id", script.project_id)
    .maybeSingle();
  // Project tier — drives the micro_drama directive block in the shotlist
  // agent's system prompt. Legacy projects default to prestige_series.
  const projectType =
    ((proj?.metadata as Record<string, unknown> | null)?.projectType as
      | string
      | undefined) ?? "prestige_series";
  let episodeNumber: number | null = null;
  let episodeTitle: string | null = null;
  if (script.episode_id) {
    const { data: ep } = await supabase
      .from("episodes")
      .select("number, title, title_status")
      .eq("id", script.episode_id)
      .maybeSingle();
    if (ep) {
      episodeNumber = ep.number as number;
      episodeTitle = ep.title_status === "approved" ? ((ep.title as string) ?? null) : null;
    }
  }
  const sceneCharNames: string[] = Array.isArray(scene.tags)
    ? (scene.tags as unknown[]).filter((x): x is string => typeof x === "string")
    : [];
  const { data: bibleChars } = await supabase
    .from("characters")
    .select("name, biography, voice_notes, metadata")
    .eq("project_id", script.project_id);
  // Cast bible biographies are story-spine prose — they include profession,
  // backstory, psychology, etc. The shotlist agent must see only filmable
  // visual descriptors, otherwise it echoes bio straight into the brief's
  // characters[].description. Hard rule: cast bible never reaches the agent
  // in raw form. Route through filmableDescriptors which drops every token
  // outside the appearance allowlist.
  const cast: BriefCharacter[] = sceneCharNames.map((name) => {
    const row = (bibleChars ?? []).find(
      (c) => (c.name as string).toUpperCase() === name.toUpperCase()
    );
    const dna =
      ((row?.metadata as Record<string, unknown>)?.dna as
        | Record<string, unknown>
        | undefined) ?? {};
    // Try DNA appearance/wardrobe first (typically already filmable), fall
    // back to public_mask, then biography. Whatever we pick, strip it.
    const appearanceSource =
      (dna.appearance as string) ??
      (dna.public_mask as string) ??
      (row?.biography as string) ??
      "";
    const wardrobeSource = (dna.wardrobe as string) ?? "";
    const desc = filmableDescriptors(appearanceSource);
    return {
      name,
      description: desc,
      wardrobe: wardrobeSource ? wardrobeSource.slice(0, 80) : undefined,
    };
  });
  const rules = await getProductionRules(script.project_id as string);
  return {
    scriptId,
    projectId: script.project_id as string,
    metadata: safeMeta(script.metadata),
    projectTitle: (proj?.title as string) ?? "Untitled",
    tone: (proj?.tone as string[] | null) ?? [],
    showrunnerNotes: (proj?.showrunner_notes as string | null) ?? null,
    episodeNumber,
    episodeTitle,
    cast,
    slugline: (scene.slugline as string) ?? `SCENE ${sceneOrd}`,
    fountain: scene.fountain as string,
    prefer: rules.prefer,
    avoid: rules.avoid,
    projectType,
  };
}

/**
 * Auto-build briefs for one scene. Replaces or fills-empty per opts.
 * Refuses to overwrite briefs flagged userEdited=true unless the caller
 * passes confirmOverwriteUserEdits=true.
 */
export async function autoBuildSceneBriefs(args: {
  scriptId: string;
  sceneOrd: number;
  opts?: AutoBuildOptions;
}): Promise<AutoBuildReport> {
  const opts: AutoBuildOptions = args.opts ?? {};
  const mode = opts.mode ?? "replace";
  const ctx = await loadAutoBuildContext(args.scriptId, args.sceneOrd);

  // Locate any existing briefs for this scene.
  const ai = safeMeta(ctx.metadata.aiPrompts);
  const allBriefs = (ai.briefs as Record<number, Record<number, MasterShotBrief>>) ?? {};
  const sceneBriefs = allBriefs[args.sceneOrd] ?? {};

  // Block-and-warn when there are user-edited briefs and confirm wasn't sent.
  const editedIndices = Object.entries(sceneBriefs)
    .filter(([, b]) => b?.userEdited === true)
    .map(([k]) => parseInt(k, 10));
  if (
    mode === "replace" &&
    editedIndices.length > 0 &&
    !opts.confirmOverwriteUserEdits
  ) {
    throw new Error(
      `Refused: scene ${args.sceneOrd} has ${editedIndices.length} user-edited brief(s) (shots ${editedIndices.join(", ")}). Re-run with confirmOverwriteUserEdits=true to overwrite.`
    );
  }

  const rawShots = await callShotlistAgent({
    projectTitle: ctx.projectTitle,
    episodeNumber: ctx.episodeNumber,
    episodeTitle: ctx.episodeTitle,
    sceneOrd: args.sceneOrd,
    slugline: ctx.slugline,
    fountain: ctx.fountain,
    tone: ctx.tone,
    showrunnerNotes: ctx.showrunnerNotes,
    prefer: ctx.prefer,
    avoid: ctx.avoid,
    cast: ctx.cast,
    steering: opts.notes,
    sourceStrict: opts.sourceStrict,
    projectType: ctx.projectType,
  });

  const fallbackCast = ctx.cast.length
    ? ctx.cast
    : ([] as BriefCharacter[]);

  // V3.6 — Source-strict source text for the post-gen validator. The
  // fountain is the canonical reference; we widen the haystack with cast
  // bios, showrunner notes, and the full Bibles corpus (Character /
  // Location / Prop) so any detail backed by an approved bible counts as
  // production-canon support instead of being flagged as speculative
  // inference.
  const { buildProjectBiblesCorpus, joinSourceCorpus } = await import(
    "./sourceCorpus.js"
  );
  const bibles = await buildProjectBiblesCorpus(ctx.projectId);
  const screenplayBase = [
    ctx.fountain,
    ctx.slugline,
    ctx.tone.join(" "),
    ctx.showrunnerNotes ?? "",
    ctx.cast.map((c) => `${c.name} ${c.description}`).join(" "),
    ctx.prefer.join(" "),
  ].join("\n");
  const sourceText = joinSourceCorpus(screenplayBase, bibles);

  // Build the new briefs, indexed from 1. In every mode we classify
  // confidence per field; in strict mode we additionally strip speculative.
  const generated: MasterShotBrief[] = rawShots.map((raw, i) => {
    const base = rawToBrief({
      raw,
      index: i + 1,
      projectTitle: ctx.projectTitle,
      episodeNumber: ctx.episodeNumber,
      episodeTitle: ctx.episodeTitle,
      sceneOrd: args.sceneOrd,
      slugline: ctx.slugline,
      fallbackCast,
    });
    if (opts.sourceStrict) {
      const result = strictCleanBrief(base, sourceText);
      return result.cleaned;
    }
    // Non-strict: emit confidence labels so the UI can warn the writer
    // without changing the content.
    const { fieldConfidence } = classifyBriefFields(base, sourceText);
    return { ...base, fieldConfidence };
  });

  // Merge per mode.
  const nextSceneBriefs: Record<number, MasterShotBrief> = {};
  const preserved: number[] = [];
  if (mode === "fill-empty") {
    // Keep every existing brief; only add new shots whose index isn't taken.
    for (const [k, v] of Object.entries(sceneBriefs)) {
      nextSceneBriefs[parseInt(k, 10)] = v;
    }
    let next = Math.max(0, ...Object.keys(nextSceneBriefs).map((k) => parseInt(k, 10))) + 1;
    for (const b of generated) {
      nextSceneBriefs[next] = { ...b, shotIndex: next, id: briefId({
        projectTitle: ctx.projectTitle,
        episodeNumber: ctx.episodeNumber,
        sceneOrd: args.sceneOrd,
        shotIndex: next,
      })};
      next++;
    }
  } else {
    // replace
    for (const b of generated) {
      nextSceneBriefs[b.shotIndex] = b;
    }
    // Preserve any existing brief flagged userEdited (and confirmed); we
    // already gated on confirm — but if confirm was sent we still log them
    // for the report so the writer sees what was overwritten.
    for (const idx of editedIndices) preserved.push(idx);
  }

  // Persist scene-safely under metadata.aiPrompts.briefs.
  const meta = { ...ctx.metadata };
  const aiMeta = { ...(safeMeta(meta.aiPrompts)) };
  const briefs = { ...((aiMeta.briefs as Record<number, Record<number, MasterShotBrief>>) ?? {}) };
  briefs[args.sceneOrd] = nextSceneBriefs;
  aiMeta.briefs = briefs;
  meta.aiPrompts = aiMeta;
  await supabase.from("scripts").update({ metadata: meta }).eq("id", args.scriptId);

  return {
    briefs: Object.values(nextSceneBriefs).sort((a, b) => a.shotIndex - b.shotIndex),
    preserved,
    sceneSlugline: ctx.slugline,
  };
}

/**
 * Patch a single brief. If the caller did not flag the patch as system-led,
 * we set userEdited=true so subsequent Auto-build runs know to preserve it
 * unless the writer confirms an overwrite.
 */
export async function patchBriefFields(args: {
  scriptId: string;
  sceneOrd: number;
  shotIndex: number;
  patch: Partial<MasterShotBrief>;
  systemEdit?: boolean;
}): Promise<MasterShotBrief> {
  const { data: script } = await supabase
    .from("scripts")
    .select("metadata")
    .eq("id", args.scriptId)
    .single();
  if (!script) throw new Error("Script not found.");
  const meta = safeMeta(script.metadata);
  const aiMeta = safeMeta(meta.aiPrompts);
  const briefs = ((aiMeta.briefs as Record<number, Record<number, MasterShotBrief>>) ?? {}) as Record<
    number,
    Record<number, MasterShotBrief>
  >;
  const sceneBriefs = briefs[args.sceneOrd] ?? {};
  const existing = sceneBriefs[args.shotIndex];
  if (!existing) throw new Error("Brief not found.");
  const next: MasterShotBrief = {
    ...existing,
    ...args.patch,
    userEdited: args.systemEdit ? existing.userEdited : true,
    updatedAt: new Date().toISOString(),
  };
  sceneBriefs[args.shotIndex] = next;
  briefs[args.sceneOrd] = sceneBriefs;
  aiMeta.briefs = briefs;
  meta.aiPrompts = aiMeta;
  await supabase.from("scripts").update({ metadata: meta }).eq("id", args.scriptId);
  return next;
}

export interface RegenerateOneBriefResult {
  brief: MasterShotBrief;
  removed: StrictRemoval[];
  preservedFields: string[];
}

/**
 * Regenerate a single Master Shot Brief in a scene. Reuses the shotlist
 * agent for the whole scene (so the regenerated shot stays consistent with
 * sibling shots) and replaces ONLY the target index. Sibling briefs are
 * preserved verbatim — including userEdited ones.
 *
 * Opts:
 *   • notes        — writer steering for the regen
 *   • sourceStrict — strip speculative fields, quarantine to nonCanonNotes
 *   • fields       — restrict the regen to these field names; other fields
 *                    on the brief are preserved (used for per-field regen)
 *   • force        — overwrite even if the brief was userEdited
 */
export async function regenerateOneBrief(args: {
  scriptId: string;
  sceneOrd: number;
  shotIndex: number;
  notes?: string;
  sourceStrict?: boolean;
  fields?: string[];
  force?: boolean;
}): Promise<RegenerateOneBriefResult> {
  const ctx = await loadAutoBuildContext(args.scriptId, args.sceneOrd);
  const ai = safeMeta(ctx.metadata.aiPrompts);
  const allBriefs = (ai.briefs as Record<number, Record<number, MasterShotBrief>>) ?? {};
  const sceneBriefs = allBriefs[args.sceneOrd] ?? {};
  const existing = sceneBriefs[args.shotIndex];
  if (!existing) {
    throw new Error(
      `No brief exists at scene ${args.sceneOrd} shot ${args.shotIndex} — run Auto-build first.`
    );
  }
  if (existing.userEdited && !args.force) {
    throw new Error(
      `Brief at shot ${args.shotIndex} is user-edited. Re-run with force=true to overwrite.`
    );
  }

  const rawShots = await callShotlistAgent({
    projectTitle: ctx.projectTitle,
    episodeNumber: ctx.episodeNumber,
    episodeTitle: ctx.episodeTitle,
    sceneOrd: args.sceneOrd,
    slugline: ctx.slugline,
    fountain: ctx.fountain,
    tone: ctx.tone,
    showrunnerNotes: ctx.showrunnerNotes,
    prefer: ctx.prefer,
    avoid: ctx.avoid,
    cast: ctx.cast,
    steering: [
      args.notes ?? "",
      `Regenerating shot index ${args.shotIndex} only. Keep the rest of the scene's shot order intact.`,
      args.fields?.length
        ? `Only regenerate these fields: ${args.fields.join(", ")}. Leave any others empty so they can be merged from the existing brief.`
        : "",
    ]
      .filter(Boolean)
      .join("\n"),
    sourceStrict: args.sourceStrict,
    projectType: ctx.projectType,
  });

  // Pick the raw shot that matches our target index (1-based). Fall back to
  // the array slot if the agent didn't tag indices.
  const oneBased = (i: number) => i + 1;
  const candidate =
    rawShots.find((r) => typeof r.index === "number" && r.index === args.shotIndex) ??
    rawShots[args.shotIndex - 1] ??
    rawShots[0];
  if (!candidate) {
    throw new Error("Shotlist agent did not return a shot for the requested index.");
  }

  const fallbackCast = ctx.cast.length ? ctx.cast : ([] as BriefCharacter[]);
  const base = rawToBrief({
    raw: candidate,
    index: args.shotIndex,
    projectTitle: ctx.projectTitle,
    episodeNumber: ctx.episodeNumber,
    episodeTitle: ctx.episodeTitle,
    sceneOrd: args.sceneOrd,
    slugline: ctx.slugline,
    fallbackCast,
  });

  // Source-strict path: clean then classify; non-strict: classify only.
  // V3.6 — see autoBuild's main path: widen the corpus with project Bibles.
  const { buildProjectBiblesCorpus: buildBC, joinSourceCorpus: joinSC } = await import(
    "./sourceCorpus.js"
  );
  const biblesR = await buildBC(ctx.projectId);
  const sourceText = joinSC(
    [
      ctx.fountain,
      ctx.slugline,
      ctx.tone.join(" "),
      ctx.showrunnerNotes ?? "",
      ctx.cast.map((c) => `${c.name} ${c.description}`).join(" "),
      ctx.prefer.join(" "),
    ].join("\n"),
    biblesR
  );

  let cleaned: MasterShotBrief = base;
  let removed: StrictRemoval[] = [];
  if (args.sourceStrict) {
    const result = strictCleanBrief(base, sourceText);
    cleaned = result.cleaned;
    removed = result.removed;
  } else {
    const { fieldConfidence } = classifyBriefFields(base, sourceText);
    cleaned = { ...base, fieldConfidence };
  }

  // Per-field merge: when args.fields is provided, only those keys move
  // from `cleaned` onto the existing brief. Otherwise wholesale replace
  // (except metadata: id, createdAt, projectTitle/episode keys, autoGenerated,
  // userEdited flags handled below).
  const preservedFields: string[] = [];
  let next: MasterShotBrief;
  if (args.fields?.length) {
    const patch: Record<string, unknown> = {};
    for (const f of args.fields) {
      patch[f] = (cleaned as Record<string, unknown>)[f];
    }
    // Merge fieldConfidence per field (overwrite only the regenerated keys).
    const mergedFC = { ...(existing.fieldConfidence ?? {}) };
    if (cleaned.fieldConfidence) {
      for (const f of args.fields) {
        const k = f as keyof typeof mergedFC;
        if (cleaned.fieldConfidence[k] !== undefined) {
          mergedFC[k] = cleaned.fieldConfidence[k];
        }
      }
    }
    next = {
      ...existing,
      ...(patch as Partial<MasterShotBrief>),
      fieldConfidence: mergedFC,
      // Per-field regen does NOT mark the whole brief as a fresh auto-gen;
      // preserve userEdited so any prior writer fields stay protected.
      autoGenerated: existing.autoGenerated,
      userEdited: existing.userEdited,
      // Carry the strict quarantine block if generated.
      nonCanonNotes: cleaned.nonCanonNotes ?? existing.nonCanonNotes,
      updatedAt: new Date().toISOString(),
    };
    for (const k of Object.keys(existing)) {
      if (!args.fields.includes(k)) preservedFields.push(k);
    }
  } else {
    next = {
      ...cleaned,
      id: existing.id,
      projectTitle: existing.projectTitle,
      episodeNumber: existing.episodeNumber,
      episodeTitle: existing.episodeTitle,
      sceneOrd: existing.sceneOrd,
      shotIndex: existing.shotIndex,
      // Whole-brief regen: this is auto-generated; userEdited is cleared
      // unless the caller forced over an edited brief — then keep the flag
      // off too so the next pass behaves like a fresh auto-build.
      autoGenerated: true,
      userEdited: false,
      // Preserve writer-supplied per-field markers when present.
      userEditedFields: existing.userEditedFields,
      createdAt: existing.createdAt,
      updatedAt: new Date().toISOString(),
    };
  }

  // Persist.
  const meta = { ...ctx.metadata };
  const aiMeta = { ...(safeMeta(meta.aiPrompts)) };
  const briefs = { ...((aiMeta.briefs as Record<number, Record<number, MasterShotBrief>>) ?? {}) };
  briefs[args.sceneOrd] = { ...(briefs[args.sceneOrd] ?? {}) };
  briefs[args.sceneOrd][args.shotIndex] = next;
  aiMeta.briefs = briefs;
  meta.aiPrompts = aiMeta;
  await supabase.from("scripts").update({ metadata: meta }).eq("id", args.scriptId);

  return { brief: next, removed, preservedFields };
}
