// Storage + version history for relationship records. Lives under
// relationships.metadata.fields. Version labels mirror the user's spec:
//
//   SELVAJE_REL_Margot_Solano_v1_Generated
//   SELVAJE_REL_Margot_Solano_v1.1_NotesPass
//   SELVAJE_REL_Margot_Solano_v1.2_UserEdit
//   SELVAJE_REL_Margot_Solano_v1.3_Approved
//
// Major version increments on full regen; decimal increments on
// notes-pass / partial regen / user edits / approval.

import { supabase } from "../../db/client.js";
import {
  ALL_GEN_FIELDS,
  assembleGeneratorContext,
  generateRelationship,
  type Importance,
  type RelationshipDraft,
} from "./generator.js";
import {
  validateStrict,
  mergeQuarantineIntoNotes,
  type StrictRemoval,
} from "./sourceStrict.js";
import { auditCanon, type FieldConfidence } from "./canonAudit.js";

type Json = Record<string, unknown>;

export interface RelationshipFieldsPersisted extends RelationshipDraft {
  pairingName?: string;
  importance?: Importance;
  approvalStatus?: "draft" | "needs_review" | "approved";
  generatedByAI?: boolean;
  userEdited?: boolean;
  approved?: boolean;
  approvedAt?: string;
  generatedAt?: string;
  lastRegeneratedAt?: string;
  sourceMaterialsUsed?: string[];
  generationNotes?: string;
  history?: VersionEntry[];
  /** Slug used to build version labels — defaults to "<A>_<B>" first names. */
  versionStem?: string;
  /** Most recent version label (e.g. "SELVAJE_REL_Margot_Solano_v1.2_UserEdit"). */
  currentVersionLabel?: string;
  /** True when this record was created by auto-suggest. */
  autoGenerated?: boolean;
  /** Free-text reason auto-suggest set for this record (e.g. "protagonist ↔ antagonist"). */
  suggestionReason?: string;
  /** Set true when the most recent generation pass was source-strict. */
  sourceStrictApplied?: boolean;
  /** What the strict validator stripped on the most recent pass — drives UI diff. */
  lastStrictRemoved?: StrictRemoval[];
  /** Per-main-field canon confidence after the auditor pass. */
  fieldConfidence?: Partial<Record<string, FieldConfidence>>;
}

export type VersionType =
  | "Generated"
  | "NotesPass"
  | "FieldPass"
  | "UserEdit"
  | "Approved"
  | "Reset";

export interface VersionEntry {
  versionLabel: string;
  type: VersionType;
  fieldsSnapshot: RelationshipFieldsPersisted;
  generationNotes?: string;
  createdAt: string;
}

function safeMeta(v: unknown): Json {
  return ((v ?? {}) as Json);
}

function slugSeries(title: string): string {
  return title
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase() || "UNTITLED";
}

function firstName(name: string): string {
  return (name.split(/\s+/)[0] ?? name).replace(/[^A-Za-z0-9]+/g, "");
}

function nextVersionLabel(
  series: string,
  stem: string,
  prev: { current?: string; history?: VersionEntry[] },
  type: VersionType
): string {
  const labels = [prev.current, ...((prev.history ?? []).map((h) => h.versionLabel))].filter(
    Boolean
  ) as string[];
  if (type === "Generated") {
    const majors = labels
      .map((l) => {
        const m = l.match(/_v(\d+)\./);
        return m ? parseInt(m[1], 10) : null;
      })
      .filter((n): n is number => typeof n === "number");
    const next = (majors.length ? Math.max(...majors) : 0) + 1;
    return `${series}_REL_${stem}_v${next}.0_Generated`;
  }
  // Decimal bump under the latest major.
  const latestMajor = (() => {
    const m = (prev.current ?? "").match(/_v(\d+)\./);
    return m ? parseInt(m[1], 10) : 1;
  })();
  const minors = labels
    .map((l) => {
      const m = l.match(new RegExp(`_v${latestMajor}\\.(\\d+)`));
      return m ? parseInt(m[1], 10) : null;
    })
    .filter((n): n is number => typeof n === "number");
  const nextMinor = (minors.length ? Math.max(...minors) : 0) + 1;
  return `${series}_REL_${stem}_v${latestMajor}.${nextMinor}_${type}`;
}

interface RelRow {
  id: string;
  project_id: string;
  a_id: string;
  b_id: string;
  nature: string | null;
  tension: string | null;
  metadata: { fields?: RelationshipFieldsPersisted } | null;
}

async function loadRel(relationshipId: string): Promise<{
  row: RelRow;
  projectTitle: string;
  aName: string;
  bName: string;
}> {
  const { data: r, error } = await supabase
    .from("relationships")
    .select("id, project_id, a_id, b_id, nature, tension, metadata")
    .eq("id", relationshipId)
    .single();
  if (error) throw error;
  const { data: proj } = await supabase
    .from("projects")
    .select("title")
    .eq("id", r.project_id)
    .maybeSingle();
  const ids = [r.a_id, r.b_id];
  const { data: chars } = await supabase
    .from("characters")
    .select("id, name")
    .in("id", ids);
  const byId = new Map((chars ?? []).map((c) => [c.id as string, c.name as string]));
  return {
    row: r as RelRow,
    projectTitle: (proj?.title as string) ?? "Untitled",
    aName: byId.get(r.a_id as string) ?? "A",
    bName: byId.get(r.b_id as string) ?? "B",
  };
}

/**
 * Run the relationship agent and persist the result with provenance + a
 * new version snapshot. Locked / approved records require the caller to
 * explicitly opt in via `force` to be regenerated.
 */
export async function generateAndStore(args: {
  relationshipId: string;
  fields?: (keyof RelationshipDraft)[];
  notes?: string;
  /** Override the approved guard. */
  force?: boolean;
  /** Strict mode — forbid invented specifics + run the post-validator. */
  sourceStrict?: boolean;
}): Promise<RelRow> {
  const { row, projectTitle, aName, bName } = await loadRel(args.relationshipId);
  const prevMeta = safeMeta(row.metadata);
  const prev: RelationshipFieldsPersisted = (prevMeta.fields as RelationshipFieldsPersisted) ?? {};
  if (prev.approved && !args.force) {
    throw new Error(
      "This relationship is approved. Reset it to draft or use force=true to regenerate."
    );
  }

  // Build the generator context once (cheap — single project read).
  const ctx = await assembleGeneratorContext(row.project_id);
  const a = ctx.characters.find((c) => c.id === row.a_id);
  const b = ctx.characters.find((c) => c.id === row.b_id);
  if (!a || !b)
    throw new Error("Couldn't resolve both characters for this pairing.");

  const draft = await generateRelationship({
    a,
    b,
    existing: prev,
    fields: args.fields,
    notes: args.notes,
    ctx,
    sourceStrict: args.sourceStrict,
  });

  // Source-strict pipeline. TWO layers:
  //   (1) Structural denylist + unsourced-entity scan — cheap, catches
  //       direct phrase matches like "the night before" / "pseudonym" /
  //       "off the record".
  //   (2) Canon auditor (second LLM call) — catches REPHRASED inventions
  //       like "she is already in the journalistic shorthand of [..]" where
  //       the LLM dodged the denylist by softening the wording.
  // Both passes strip from main fields and feed the quarantine block in
  // Internal Notes. Per-field confidence comes from the auditor.
  let strictRemovals: StrictRemoval[] = [];
  let quarantineNotes = "";
  let validated: RelationshipDraft = draft;
  let fieldConfidence: Partial<Record<string, FieldConfidence>> = {};
  if (args.sourceStrict) {
    const sourceTextBlock = [
      ctx.synopsis ?? "",
      ctx.worldStatement ?? "",
      ctx.seasonArc ?? "",
      (ctx.themes ?? []).join(" "),
      ctx.showrunnerNotes ?? "",
      (ctx.episodes ?? [])
        .map((e) => `${e.title ?? ""} ${e.logline ?? ""}`)
        .join(" "),
      a.bio ?? "",
      b.bio ?? "",
      ctx.productionRules?.prefer.join(" ") ?? "",
    ].join("\n");

    // Layer 1: structural.
    const struct = validateStrict(draft, sourceTextBlock, [a.name, b.name]);
    validated = struct.cleaned;
    strictRemovals = struct.removed;
    quarantineNotes = struct.quarantine;

    // Layer 2: LLM auditor. Only worth running when there's still content.
    const hasContent = Object.values(validated).some(
      (v) => typeof v === "string" && v.trim().length > 0
    );
    if (hasContent) {
      try {
        const audit = await auditCanon({
          draft: validated,
          sourceManifest: sourceTextBlock,
          aName: a.name,
          bName: b.name,
          allowedThematicTokens: ctx.productionRules?.prefer ?? [],
        });
        validated = audit.cleaned;
        // Combine removals from both layers (dedupe is unnecessary —
        // the structural pass already stripped its sentences before the
        // auditor saw them).
        if (audit.removed.length) {
          strictRemovals = [...strictRemovals, ...audit.removed];
          const lines = ["Possible future story idea — not canon"];
          for (const r of audit.removed) {
            lines.push(`• [${String(r.field)}] (${r.reason}) ${r.snippet}`);
          }
          // Merge into the existing quarantine block.
          quarantineNotes = quarantineNotes
            ? `${quarantineNotes}\n${lines.slice(1).join("\n")}`
            : lines.join("\n");
        }
        fieldConfidence = audit.fieldConfidence;
      } catch {
        // Auditor failed — keep the structural-only result. Better to ship
        // the safer subset than fail the whole regeneration.
      }
    }
  }

  // Merge VALIDATED draft into prior fields; preserve fields the caller
  // didn't ask to regenerate. In source-strict mode the validator has
  // already stripped invented specifics; in normal mode validated === draft.
  const merged: RelationshipFieldsPersisted = { ...prev };
  // CRITICAL for source-strict: when the writer asks for strict regen, we
  // OVERWRITE the listed (or all) fields wholesale rather than preserving
  // prior copy. Otherwise removed specifics would persist from the prior
  // version. In non-strict mode we keep the existing merge behavior.
  if (args.sourceStrict) {
    const targets =
      args.fields && args.fields.length > 0
        ? (args.fields as (keyof RelationshipDraft)[])
        : (Object.keys(validated) as (keyof RelationshipDraft)[]);
    for (const k of targets) {
      const v = (validated as Record<string, unknown>)[k];
      // Even if the validator removed everything from a sentence and the
      // result is now empty, we still WRITE the empty string so the prior
      // unsourced content is gone. UI will surface this as a missing
      // source warning rather than carrying stale invention.
      (merged as Record<string, unknown>)[k] = typeof v === "string" ? v : "";
    }
  } else {
    for (const k of Object.keys(draft) as (keyof RelationshipDraft)[]) {
      const v = (draft as Record<string, unknown>)[k];
      if (v !== undefined) (merged as Record<string, unknown>)[k] = v;
    }
  }
  // Quarantine non-canon ideas into Internal Notes (strict mode only).
  if (args.sourceStrict && quarantineNotes) {
    merged.internalNotes = mergeQuarantineIntoNotes(
      typeof merged.internalNotes === "string" ? merged.internalNotes : undefined,
      quarantineNotes
    );
  }
  merged.sourceStrictApplied = !!args.sourceStrict;
  merged.lastStrictRemoved = args.sourceStrict ? strictRemovals : undefined;
  if (args.sourceStrict) {
    merged.fieldConfidence = fieldConfidence;
  }
  // Provenance.
  const now = new Date().toISOString();
  merged.generatedByAI = true;
  if (!merged.generatedAt) merged.generatedAt = now;
  merged.lastRegeneratedAt = now;
  if (args.notes) merged.generationNotes = args.notes;
  merged.sourceMaterialsUsed = [
    ...(ctx.synopsis ? ["synopsis"] : []),
    ...(ctx.seasonArc ? ["seasonArc"] : []),
    ...(ctx.episodes.length ? [`episodes(${ctx.episodes.length})`] : []),
    ...(a.dna || b.dna ? ["characterDNA"] : []),
    ...(a.wound || b.wound ? ["characterWounds"] : []),
    ...(ctx.showrunnerNotes ? ["showrunnerNotes"] : []),
    ...(ctx.productionRules ? ["productionRules"] : []),
  ];
  // Default approval status / importance preserved.
  if (!merged.approvalStatus) merged.approvalStatus = "draft";
  if (!merged.importance) merged.importance = prev.importance ?? "secondary";
  if (!merged.pairingName) merged.pairingName = prev.pairingName ?? `${aName} ↔ ${bName}`;
  if (!merged.versionStem) merged.versionStem = prev.versionStem ?? `${firstName(aName)}_${firstName(bName)}`;

  // Version label.
  const series = slugSeries(projectTitle);
  const stem = merged.versionStem!;
  const versionType: VersionType = !prev.currentVersionLabel
    ? "Generated"
    : args.notes
    ? "NotesPass"
    : args.fields && args.fields.length < ALL_GEN_FIELDS.length
    ? "FieldPass"
    : "Generated";
  const label = nextVersionLabel(
    series,
    stem,
    { current: prev.currentVersionLabel, history: prev.history },
    versionType
  );
  const history = [
    ...(prev.history ?? []),
    {
      versionLabel: label,
      type: versionType,
      fieldsSnapshot: { ...merged } as RelationshipFieldsPersisted,
      generationNotes: args.notes,
      createdAt: now,
    } satisfies VersionEntry,
  ].slice(-15);
  merged.history = history;
  merged.currentVersionLabel = label;

  // Mirror legacy flat columns so existing readers still see something.
  const nature = merged.nature ?? row.nature ?? null;
  const tension = merged.coreTension ?? row.tension ?? null;
  const { data: updated, error } = await supabase
    .from("relationships")
    .update({
      nature,
      tension,
      metadata: { ...prevMeta, fields: merged },
    })
    .eq("id", row.id)
    .select("*")
    .single();
  if (error) throw error;
  return updated as RelRow;
}

/** Flip `approvalStatus` + `approved` + timestamp. */
export async function approveRelationship(
  relationshipId: string,
  approved: boolean
): Promise<RelRow> {
  const { row, projectTitle, aName, bName } = await loadRel(relationshipId);
  const prevMeta = safeMeta(row.metadata);
  const prev: RelationshipFieldsPersisted = (prevMeta.fields as RelationshipFieldsPersisted) ?? {};
  const now = new Date().toISOString();
  const next: RelationshipFieldsPersisted = {
    ...prev,
    approvalStatus: approved ? "approved" : "draft",
    approved,
    approvedAt: approved ? now : undefined,
  };
  // Snapshot a decimal version.
  const series = slugSeries(projectTitle);
  const stem = prev.versionStem ?? `${firstName(aName)}_${firstName(bName)}`;
  const label = nextVersionLabel(
    series,
    stem,
    { current: prev.currentVersionLabel, history: prev.history },
    approved ? "Approved" : "Reset"
  );
  next.versionStem = stem;
  next.currentVersionLabel = label;
  next.history = [
    ...(prev.history ?? []),
    {
      versionLabel: label,
      type: approved ? "Approved" : "Reset",
      fieldsSnapshot: { ...next } as RelationshipFieldsPersisted,
      createdAt: now,
    },
  ].slice(-15);
  const { data: updated, error } = await supabase
    .from("relationships")
    .update({ metadata: { ...prevMeta, fields: next } })
    .eq("id", row.id)
    .select("*")
    .single();
  if (error) throw error;
  return updated as RelRow;
}

/**
 * Persist a writer-supplied patch (UI editor). Bumps a decimal version
 * snapshot tagged "UserEdit" so the history records the writer's pass.
 */
export async function patchAndSnapshot(
  relationshipId: string,
  patch: Partial<RelationshipFieldsPersisted>
): Promise<RelRow> {
  const { row, projectTitle, aName, bName } = await loadRel(relationshipId);
  const prevMeta = safeMeta(row.metadata);
  const prev: RelationshipFieldsPersisted = (prevMeta.fields as RelationshipFieldsPersisted) ?? {};
  const isContentEdit = (
    [
      "nature",
      "aWants",
      "bWants",
      "aWithholds",
      "bWithholds",
      "coreTension",
      "powerDynamic",
      "emotionalCost",
      "dramaticFunction",
      "buyerSummary",
      "internalNotes",
      "pairingName",
    ] as (keyof RelationshipFieldsPersisted)[]
  ).some((k) => patch[k] !== undefined);
  const next: RelationshipFieldsPersisted = { ...prev, ...patch };
  if (isContentEdit) next.userEdited = true;

  if (isContentEdit) {
    const now = new Date().toISOString();
    const series = slugSeries(projectTitle);
    const stem = next.versionStem ?? `${firstName(aName)}_${firstName(bName)}`;
    const label = nextVersionLabel(
      series,
      stem,
      { current: prev.currentVersionLabel, history: prev.history },
      "UserEdit"
    );
    next.versionStem = stem;
    next.currentVersionLabel = label;
    next.history = [
      ...(prev.history ?? []),
      {
        versionLabel: label,
        type: "UserEdit",
        fieldsSnapshot: { ...next } as RelationshipFieldsPersisted,
        createdAt: now,
      },
    ].slice(-15);
  }

  const { data: updated, error } = await supabase
    .from("relationships")
    .update({
      nature: next.nature ?? row.nature ?? null,
      tension: next.coreTension ?? row.tension ?? null,
      metadata: { ...prevMeta, fields: next },
    })
    .eq("id", row.id)
    .select("*")
    .single();
  if (error) throw error;
  return updated as RelRow;
}
